language: node_js
node_js:
  - "11.10.1"
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: my-ecommerce-ep
  on: master 
  strategy: git
install:
  - npm install
before_script:
  - export CODE_COVERAGE_TOKEN=$CODE_COVERAGE_TOKEN
script:
  - npm run write-coveralls
  - npm test